### PR TITLE
add NATIPKG option

### PR DESCRIPTION
**Pull request by mbutterick**
prepending NATIPKG=1 as an env var will choose the "natipkg" build variants (where available).

### CODE REVIEW

**Comment by greghendershott** [comment]
Thanks!

I wonder if it should be `RACKET_NATIPKG` instead of `NATIPKG`? Maybe why:

- More like existing options `RACKET_VERSION` and `RACKET_MINIMAL`.

- Like those, would be easier to spot -- in a `.travis.yml` or in Travis CI web UI -- that it's a Racket option. (Some projects mix tools. For instance racket-mode has a mix of `RACKET_*` and `EMACS_*` vars.)

**Comment by mbutterick** [comment]
I leave it to your good judgment. Makes sense if that is the convention thus far.

**Comment by greghendershott** [comment]
I think `RACKET_NATIPKG` would be better, if you don't mind making that change?

**Comment by greghendershott** [comment]
Thanks -- merged!

**Pull request merged**
