### PR TITLE
Overhaul install-racket.sh and add test.sh to validate full matrix.

### PR DESCRIPTION
**Pull request by zenspider**
Namely, added test.sh to run through all the possible downloads and test for validity.

Added handler for TEST=1 in install-racket.sh.

Normalize urls as much as possible and to get minimal installs working
properly. This can probably be merged to master and drop the minimal
branch entirely.

I think there is still some cleanup that can happen. The various linux
flavors can probably be unified, if not parameterized.

This patch removes SCOPE_SNAPSHOT, as it seems to point to incredibly
stale content. RELEASE does too, but there is a note that it is only
valid during release phases.

### CODE REVIEW

**Comment by zenspider** [comment]
Here is the current output:

```
0 6.6     http://download.racket-lang.org/installers/6.6/racket-6.6-x86_64-linux.sh                                                GOOD
1 6.6     http://download.racket-lang.org/installers/6.6/racket-minimal-6.6-x86_64-linux.sh                                        GOOD
0 6.5     http://download.racket-lang.org/installers/6.5/racket-6.5-x86_64-linux.sh                                                GOOD
1 6.5     http://download.racket-lang.org/installers/6.5/racket-minimal-6.5-x86_64-linux.sh                                        GOOD
0 6.4     http://download.racket-lang.org/installers/6.4/racket-6.4-x86_64-linux-ubuntu-precise.sh                                 GOOD
1 6.4     http://download.racket-lang.org/installers/6.4/racket-minimal-6.4-x86_64-linux-ubuntu-precise.sh                         GOOD
0 6.3     http://download.racket-lang.org/installers/6.3/racket-6.3-x86_64-linux-ubuntu-precise.sh                                 GOOD
1 6.3     http://download.racket-lang.org/installers/6.3/racket-minimal-6.3-x86_64-linux-ubuntu-precise.sh                         GOOD
0 6.2     http://download.racket-lang.org/installers/6.2/racket-6.2-x86_64-linux-ubuntu-precise.sh                                 GOOD
1 6.2     http://download.racket-lang.org/installers/6.2/racket-minimal-6.2-x86_64-linux-ubuntu-precise.sh                         GOOD
0 6.2.1   http://download.racket-lang.org/installers/6.2.1/racket-6.2.1-x86_64-linux-ubuntu-precise.sh                             GOOD
1 6.2.1   http://download.racket-lang.org/installers/6.2.1/racket-minimal-6.2.1-x86_64-linux-ubuntu-precise.sh                     GOOD
0 6.1     http://download.racket-lang.org/installers/6.1/racket-6.1-x86_64-linux-ubuntu-precise.sh                                 GOOD
1 6.1     http://download.racket-lang.org/installers/6.1/racket-minimal-6.1-x86_64-linux-ubuntu-precise.sh                         GOOD
0 6.1.1   http://download.racket-lang.org/installers/6.1.1/racket-6.1.1-x86_64-linux-ubuntu-precise.sh                             GOOD
1 6.1.1   http://download.racket-lang.org/installers/6.1.1/racket-minimal-6.1.1-x86_64-linux-ubuntu-precise.sh                     GOOD
0 6.0     http://download.racket-lang.org/installers/6.0/racket-6.0-x86_64-linux-ubuntu-precise.sh                                 GOOD
1 6.0     http://download.racket-lang.org/installers/6.0/racket-minimal-6.0-x86_64-linux-ubuntu-precise.sh                         GOOD
0 6.0.1   http://download.racket-lang.org/installers/6.0.1/racket-6.0.1-x86_64-linux-ubuntu-precise.sh                             GOOD
1 6.0.1   http://download.racket-lang.org/installers/6.0.1/racket-minimal-6.0.1-x86_64-linux-ubuntu-precise.sh                     GOOD
0 5.93    http://download.racket-lang.org/installers/5.93/racket-5.93-x86_64-linux-ubuntu-quantal.sh                               GOOD
1 5.93    http://download.racket-lang.org/installers/5.93/racket-minimal-5.93-x86_64-linux-ubuntu-quantal.sh                       GOOD
0 5.92    http://download.racket-lang.org/installers/5.92/racket-5.92-x86_64-linux-ubuntu-quantal.sh                               GOOD
1 5.92    http://download.racket-lang.org/installers/5.92/racket-minimal-5.92-x86_64-linux-ubuntu-quantal.sh                       GOOD
0 5.3     http://download.racket-lang.org/installers/5.3/racket/racket-5.3-bin-x86_64-linux-debian-squeeze.sh                      GOOD
1 5.3     http://download.racket-lang.org/installers/5.3/racket-textual/racket-textual-5.3-bin-x86_64-linux-debian-squeeze.sh      GOOD
0 5.3.6   http://download.racket-lang.org/installers/5.3.6/racket/racket-5.3.6-bin-x86_64-linux-debian-squeeze.sh                  GOOD
1 5.3.6   http://download.racket-lang.org/installers/5.3.6/racket-textual/racket-textual-5.3.6-bin-x86_64-linux-debian-squeeze.sh  GOOD
0 5.3.5   http://download.racket-lang.org/installers/5.3.5/racket/racket-5.3.5-bin-x86_64-linux-debian-squeeze.sh                  GOOD
1 5.3.5   http://download.racket-lang.org/installers/5.3.5/racket-textual/racket-textual-5.3.5-bin-x86_64-linux-debian-squeeze.sh  GOOD
0 5.3.4   http://download.racket-lang.org/installers/5.3.4/racket/racket-5.3.4-bin-x86_64-linux-debian-squeeze.sh                  GOOD
1 5.3.4   http://download.racket-lang.org/installers/5.3.4/racket-textual/racket-textual-5.3.4-bin-x86_64-linux-debian-squeeze.sh  GOOD
0 5.3.3   http://download.racket-lang.org/installers/5.3.3/racket/racket-5.3.3-bin-x86_64-linux-debian-squeeze.sh                  GOOD
1 5.3.3   http://download.racket-lang.org/installers/5.3.3/racket-textual/racket-textual-5.3.3-bin-x86_64-linux-debian-squeeze.sh  GOOD
0 5.3.2   http://download.racket-lang.org/installers/5.3.2/racket/racket-5.3.2-bin-x86_64-linux-debian-squeeze.sh                  GOOD
1 5.3.2   http://download.racket-lang.org/installers/5.3.2/racket-textual/racket-textual-5.3.2-bin-x86_64-linux-debian-squeeze.sh  GOOD
0 5.3.1   http://download.racket-lang.org/installers/5.3.1/racket/racket-5.3.1-bin-x86_64-linux-debian-squeeze.sh                  GOOD
1 5.3.1   http://download.racket-lang.org/installers/5.3.1/racket-textual/racket-textual-5.3.1-bin-x86_64-linux-debian-squeeze.sh  GOOD
0 HEAD    http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh                GOOD
1 HEAD    http://plt.eecs.northwestern.edu/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh                 GOOD
0 RELEASE http://pre-release.racket-lang.org/installers/racket-current-x86_64-linux.sh                                             GOOD
1 RELEASE http://pre-release.racket-lang.org/installers/racket-minimal-current-x86_64-linux.sh                                     GOOD
```

**Comment by greghendershott** [comment]
This is fantastic -- thanks!!

> This patch removes SCOPE_SNAPSHOT, as it seems to point to incredibly stale content

That's my only concern -- people may have existing `.travis.yml` files that use this in the build matrix.

In fact as of this commit [the example `.travis.yml` still does](https://github.com/greghendershott/travis-racket/blob/master/.travis.yml#L33).

Although admittedly `SCOPE_SNAPSHOT` is long since N/A, I don't like that some people would suddenly get the build-failed red badge of shame.

One idea:

1. Remove `SCOPE_SNAPSHOT` from the example `.travis.yml`.

2. Have `install-racket.sh` keep `SCOPE_SNAPSHOT` but make it a no-op. Maybe it prints a deprecation message and does an `exit 0` success.

What do you think?

**Comment by zenspider** [comment]
> 1. Remove SCOPE_SNAPSHOT from the example .travis.yml.

Oops. I had in my original incarnation. I must have missed this when I redid it.

This is done.

> 2. Have install-racket.sh keep SCOPE_SNAPSHOT but make it a no-op. Maybe it prints a deprecation message and does an exit 0 success.

It doesn't make sense to me for it to exit 0 and make whatever build is following blow up because racket isn't there. Then again, any current build that is depending on this must be blown up already, right? It hasn't been valid for a couple years it seems. Maybe it should install a default instead?

**Comment by zenspider** [comment]
I've removed SCOPE_SNAPSHOT from .travis.yml. Let me know if you want anything else.

**Comment by greghendershott** [comment]
> It doesn't make sense to me for it to exit 0 and make whatever build is following blow up because racket isn't there.

Derp. Yes. I was mixing levels (the travis.yml and the install.sh).

> It hasn't been valid for a couple years it seems.

Oh OK. I didn't realize the scopes build was no longer available.  If it's already going to error, this won't make things any worse.

Thanks again!

**Comment by zenspider** [comment]
@greghendershott can you merge master onto minimal (or recreate minimal from master)?

**Comment by greghendershott** [comment]
I don't understand. Why?

(As best I recall, `minimal` is just a topic branch with year-old commits; probably I should have done some housekeeping and deleted it. The only non-topic branch of use to people is `master`.)

**Comment by zenspider** [comment]
Exercism.io, at least, was directly using minimal in their build scripts. Maybe that was an anomaly, but I wanted to ensure that anyone using that recipe was essentially on master.

I can also get behind deleting.

**Pull request merged**
